name: Backend Tests
run-name: Run tests for backend
on: push
jobs:
  Run-unittests-and-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unittests
        run: pytest
      - name: Run pylint
        run: pylint --fail-under=9.0 routers/ services/ db/ schemas/ main.py
  Repository-dispatch:
      # Only run if tests succeed and the branch in main
      if: (needs.Run-unittests-and-pylint == 'success') && (github.ref == 'refs/heads/main')
      needs: Run-unittests-and-pylint
      runs-on: ubuntu-latest
      steps:
        - name: Do repository dispatch
          run: |
            curl -XPOST -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/TinyMLaas/TinyMLaaS/dispatches --data '{"event_type": "Backend-Trigger"}'
